### ISSUE TITLE
Small typo in README

### ISSUE THREAD

**Issue by mtvector** [ebi-gene-expression-group/dropletutils-scripts#6]
Hey, great package, thanks for putting it together for non R users like me! Totally made my decision to apply the tool. Just wanted to point out in readme you have "dropletutils-read-10-countsx.R" instead of "dropletutils-read-10x-counts.R". Just a little hitch for ctrl+c ctrl+v people like me!

**Comment by pinin4fjords** [comment]
Glad you're finding it useful! Thanks for spotting the typo, fixed now.
